version: "3"

services:
  order-manager-db:
    image: postgres:15
    container_name: order-manager-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_USER: postgres
      POSTGRES_DB: order-manager-db
    volumes:
      - ./order_manager_db:/var/lib/postgresql/data
    networks:
      - order-manager-network

  order-manager-back:
    image: om-back-java
    container_name: order-manager-back-java
    ports:
      - "3000:3000"
    depends_on:
      - order-manager-db
    environment:
      TYPEORM_HOST: order-manager-db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: p0stgr3s
      TYPEORM_DATABASE: order-manager-db
      NODE_ENV: production
    networks:
      - order-manager-network

networks:
  order-manager-network:
    driver: bridge
